version: "3.9"

services:
  mindmesh-app:
    build: .
    container_name: mindmesh-app
    ports:
      - "8501:8501"
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - .:/app
