apiVersion: v1
kind: Secret
metadata:
  name: mindmesh-secrets
  namespace: mindmesh
type: Opaque
stringData:
  GEMINI_API_KEY: "change_me"
  GROQ_API_KEY: "change_me"
  QDRANT_API_KEY: "change_me"
  TELEGRAM_BOT_TOKEN: "change_me"
